import { Platform, StyleSheet } from "react-native";
import STYLES from "../../constants/Styles";
import Layout from "../../constants/Layout";

export const styles = StyleSheet.create({
  icon: {
    height: Layout.normalize(40),
    width: Layout.normalize(40),
    resizeMode: "contain",
    marginRight: Layout.normalize(5),
  },
  smallIcon: {
    height: Layout.normalize(15),
    width: Layout.normalize(15),
    resizeMode: "contain",
    marginRight: Layout.normalize(5),
  },
  attachmentMessage: {
    padding: Layout.normalize(10),
    width: "80%",
    alignSelf: "flex-end",
    borderRadius: Layout.normalize(15),
    backgroundColor: "#fff",
  },
  sentMessage: {
    alignSelf: "flex-end",
    backgroundColor: STYLES.$COLORS.TERTIARY,
    borderBottomRightRadius: 0,
  },
  receivedMessage: {
    alignSelf: "flex-start",
    backgroundColor: STYLES.$COLORS.TERTIARY,
    borderBottomLeftRadius: 0,
    marginLeft: Layout.normalize(30),
  },
  alignRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: STYLES.$COLORS.JOINED_BTN,
    padding: Layout.normalize(10),
    borderRadius: Layout.normalize(5),
  },
  docName: {
    fontSize: STYLES.$FONT_SIZES.SMALL,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    color: STYLES.$COLORS.FONT_PRIMARY,
    width: "80%",
  },
  messageText: {
    fontSize: STYLES.$FONT_SIZES.SMALL,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    color: STYLES.$COLORS.FONT_PRIMARY,
    marginTop: Layout.normalize(5),
  },
  messageDate: {
    fontSize: Layout.normalize(10),
    color: "#aaa",
    textAlign: "right",
  },
  fullListCount: {
    fontSize: STYLES.$FONT_SIZES.SMALL,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    color: STYLES.$COLORS.LIGHT_BLUE,
    marginTop: Layout.normalize(5),
  },
  singleImg: {
    height: Layout.normalize(150),
    width: "100%",
    resizeMode: "cover",
  },
  doubleImgParent: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Layout.normalize(5),
  },
  doubleImg: {
    height: Layout.normalize(130),
    width: "100%",
    resizeMode: "cover",
    borderRadius: Layout.normalize(5),
  },
  multipleImg: {
    height: Layout.normalize(130),
    resizeMode: "cover",
    borderRadius: Layout.normalize(5),
  },
  imgParent: {
    flex: 1,
    resizeMode: "cover",
    borderRadius: Layout.normalize(5),
  },
  tripleImgText: {
    color: "white",
    fontSize: STYLES.$FONT_SIZES.XXL,
  },
  tripleImgOverlay: {
    position: "absolute",
    right: 0,
    height: Layout.normalize(130),
    width: "50%",
    backgroundColor: "black",
    opacity: Layout.normalize(0.5),
    borderRadius: Layout.normalize(5),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  touchableImg: { height: Layout.normalize(130), width: "49%" },
  deletedMsg: {
    color: STYLES.$COLORS.MSG,
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    fontStyle: "italic",
  },
  displayRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: Layout.normalize(10),
  },
  uploadingIndicator: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    zIndex: 1,
    height: "100%",
    width: "100%",
    backgroundColor: "white",
    opacity: Layout.normalize(0.5),
  },
  videoIcon: {
    height: Layout.normalize(20),
    width: Layout.normalize(20),
    resizeMode: "contain",
    tintColor: "white",
  },
  retryButton: {
    backgroundColor: "black",
    padding: Layout.normalize(10),
    borderRadius: Layout.normalize(50),
    flexDirection: "row",
    gap: Layout.normalize(5),
    alignItems: "center",
  },
  retryIcon: {
    height: Layout.normalize(20),
    width: Layout.normalize(20),
    resizeMode: "contain",
  },
  retryText: {
    color: "white",
    fontSize: STYLES.$FONT_SIZES.LARGE,
    fontFamily: STYLES.$FONT_TYPES.SEMI_BOLD,
    marginBottom: Layout.normalize(-1),
  },
  messageInfo: {
    color: "green",
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.BOLD,
    marginBottom: STYLES.$MARGINS.XS,
  },
  messageCustomTitle: {
    color: STYLES.$COLORS.MSG,
    fontSize: STYLES.$FONT_SIZES.SMALL,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
  },
  alignTime: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: Layout.normalize(3),
  },
  voiceNotesParentBox: {
    display: "flex",
    flexDirection: "row",
    flex: 1,
    gap: Layout.normalize(10),
    paddingVertical: Layout.normalize(5),
    paddingHorizontal: Layout.normalize(10),
  },
  playPauseBox: {
    height: Layout.normalize(40),
    width: Layout.normalize(40),
    borderRadius: Layout.normalize(30),
    backgroundColor: "#ffad31",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  playPauseImage: {
    height: Layout.normalize(30),
    width: Layout.normalize(30),
    tintColor: "white",
  },
  recordTitle: {
    fontSize: STYLES.$FONT_SIZES.SMALL,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    color: STYLES.$COLORS.MSG,
    marginTop: Platform.OS === "ios" ? Layout.normalize(3) : 0,
  },
});
