import { StyleSheet, PixelRatio, Platform } from "react-native";
import Layout from "../../constants/Layout";
import STYLES from "../../constants/Styles";

export const styles = StyleSheet.create({
  textInput: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    flexGrow: 1,
    borderRadius: Layout.normalize(30),
    width: Layout.window.width - 75,
  },
  inputBoxWithShadow: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: Layout.normalize(1) },
    shadowOpacity: Layout.normalize(0.2),
    shadowRadius: Layout.normalize(2),
    elevation: Layout.normalize(2),
  },
  inputContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    padding: Layout.normalize(5),
    margin: Layout.normalize(5),
  },
  addMoreButton: {
    padding: Layout.normalize(10),
    paddingLeft: Layout.normalize(15),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  emojiButton: {
    padding: Layout.normalize(10),
  },

  emoji: {
    width: Layout.normalize(22),
    height: Layout.normalize(22),
    resizeMode: "contain",
  },

  chevron: {
    width: Layout.normalize(12),
    height: Layout.normalize(12),
    resizeMode: "contain",
  },

  send: {
    width: Layout.normalize(22),
    height: Layout.normalize(22),
    resizeMode: "contain",
    marginLeft: Layout.normalize(5),
  },

  mic: {
    width: Layout.normalize(22),
    height: Layout.normalize(22),
    resizeMode: "contain",
  },
  inputParent: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginVertical: Layout.normalize(10),
    paddingLeft: 0,
    width: "70%",
  },
  voiceNotesInputParent: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginVertical: Layout.normalize(10),
    paddingLeft: 0,
    width: "88%",
  },
  input: {
    flexGrow: 1,
    fontSize: STYLES.$FONT_SIZES.LARGE,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    maxHeight: Layout.normalize(120),
    padding: 0,
    marginBottom: Layout.normalize(2),
    overflow: "scroll",
  },
  sendButton: {
    height: Layout.normalize(50),
    width: Layout.normalize(50),
    backgroundColor: STYLES.$COLORS.SECONDARY,
    borderRadius: Layout.normalize(50),
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: Layout.normalize(5),
  },
  sendButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: Layout.normalize(16),
  },
  emojiPicker: {
    flexDirection: "row",
    backgroundColor: "#f2f2f2",
    padding: Layout.normalize(10),
  },

  centeredView: {
    flexGrow: 1,
    marginTop: Layout.normalize(20),
  },
  modalViewParent: {
    position: "absolute",
    bottom: Layout.normalize(60),
    flexGrow: 1,
    width: Layout.window.width,
  },
  modalView: {
    margin: Layout.normalize(10),
    backgroundColor: "white",
    borderRadius: Layout.normalize(8),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: Layout.normalize(2),
    },
    padding: Layout.normalize(5),
    shadowOpacity: Layout.normalize(0.25),
    shadowRadius: Layout.normalize(4),
    elevation: Layout.normalize(5),
  },

  alignModalElements: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: Layout.normalize(20),
    flexWrap: "wrap",
    marginHorizontal: Layout.normalize(20),
  },
  cameraStyle: {
    backgroundColor: "#06C3AF",
    padding: Layout.normalize(15),
    borderRadius: Layout.normalize(50),
  },
  imageStyle: {
    backgroundColor: "#555feb",
    padding: Layout.normalize(15),
    borderRadius: Layout.normalize(50),
  },
  docStyle: {
    backgroundColor: "#e55e69",
    padding: Layout.normalize(15),
    borderRadius: Layout.normalize(50),
  },
  pollStyle: {
    backgroundColor: "#4098f7",
    padding: Layout.normalize(15),
    borderRadius: Layout.normalize(50),
  },
  replyBoxParent: {
    backgroundColor: "white",
    borderBottom: "none",
    borderBottomWidth: 0,
    borderBottomRightRadius: Layout.normalize(30),
    borderBottomLeftRadius: Layout.normalize(30),
    borderColor: STYLES.$COLORS.MSG,
    overflow: "hidden",
  },
  replyBox: {
    marginHorizontal: Layout.normalize(10),
    marginTop: Layout.normalize(10),
  },
  linkPreviewTextView: {
    marginHorizontal: Layout.normalize(10),
    marginTop: Layout.normalize(10),
    marginBottom: Layout.normalize(10),
    width: Layout.normalize(150),
  },
  linkPreviewTitle: {
    color: "black",
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.BOLD,
    overflow: "hidden",
  },
  alignRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginTop: Layout.normalize(5),
  },
  linkPreviewIcon: {
    height: Layout.normalize(80),
    width: Layout.normalize(80),
    justifyContent: "center",
    alignItems: "center",
    resizeMode: "contain",
    marginLeft: Layout.normalize(10),
    borderRadius: Layout.normalize(5),
    marginBottom: Layout.normalize(10),
  },
  linkPreviewBox: {
    display: "flex",
    flexDirection: "row",
  },
  linkPreviewMessageText: {
    fontSize: STYLES.$FONT_SIZES.SMALL,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    color: STYLES.$COLORS.FONT_PRIMARY,
    maxWidth: Layout.window.width - 150,
  },
  replyBoxClose: {
    position: "absolute",
    right: Layout.normalize(10),
    top: Layout.normalize(10),
    backgroundColor: STYLES.$COLORS.SELECTED_BLUE,
    padding: Layout.normalize(5),
    borderRadius: Layout.normalize(10),
  },
  replyCloseImg: {
    height: Layout.normalize(7),
    width: Layout.normalize(7),
    resizeMode: "contain",
  },
  iconText: {
    fontSize: STYLES.$FONT_SIZES.SMALL,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    color: STYLES.$COLORS.FONT_PRIMARY,
  },
  iconContainer: {
    alignItems: "center",
    margin: Layout.normalize(10),
    gap: Layout.normalize(5),
  },
  avatar: {
    width: Layout.normalize(30),
    height: Layout.normalize(30),
    borderRadius: STYLES.$AVATAR.BORDER_RADIUS,
    marginRight: STYLES.$MARGINS.SMALL,
  },
  lockIconStyle: {
    width: Layout.normalize(22),
    height: Layout.normalize(22),
    resizeMode: "contain",
    marginTop: Layout.normalize(20),
  },
  chevronUpStyle: {
    width: Layout.normalize(12),
    height: Layout.normalize(12),
    resizeMode: "contain",
    marginTop: Layout.normalize(20),
  },
  infoContainer: {
    flex: 1,
    paddingVertical: Layout.normalize(15),
    borderBottomColor: STYLES.$COLORS.MSG,
  },
  title: {
    fontSize: STYLES.$FONT_SIZES.LARGE,
    fontFamily: STYLES.$FONT_TYPES.MEDIUM,
    color: STYLES.$COLORS.FONT_PRIMARY,
  },
  subTitle: {
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    color: STYLES.$COLORS.MSG,
  },
  tapAndHoldStyle: {
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    color: STYLES.$COLORS.TERTIARY,
  },
  recordTitle: {
    fontSize: STYLES.$FONT_SIZES.LARGE,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    color: STYLES.$COLORS.MSG,
    marginTop: Platform.OS === "ios" ? Layout.normalize(3) : 0,
  },
  messageCustomTitle: {
    color: STYLES.$COLORS.SECONDARY,
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
  },
  taggableUsersBox: {
    borderTopRightRadius: Layout.normalize(20),
    borderTopLeftRadius: Layout.normalize(20),
    width: "100%",
    position: "relative",
    backgroundColor: "white",
    borderColor: STYLES.$COLORS.MSG,
    overflow: "hidden",
  },
  taggableUserView: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginLeft: Layout.normalize(10),
    marginTop: Layout.normalize(10),
  },
  disabledInput: {
    marginVertical:
      Platform.OS === "android" ? Layout.normalize(10) : Layout.normalize(20),
    marginHorizontal: Layout.normalize(10),
    paddingVertical: Layout.normalize(10),
    minHeight: Layout.normalize(50),
    paddingHorizontal: Layout.normalize(20),
    backgroundColor: "#f2f2f2",
    borderRadius: Layout.normalize(25),
    justifyContent: "center",
    borderColor: STYLES.$COLORS.MSG,
    borderWidth: Layout.normalize(1),
  },
  disabledInputText: {
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.MEDIUM,
    color: STYLES.$COLORS.MSG,
  },
  alignItems: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: Layout.normalize(10),
    textAlign: "center",
  },
  voiceRecorderInput: {
    marginHorizontal: Layout.normalize(20),
    paddingVertical: Layout.normalize(4),
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  lockRecording: {
    backgroundColor: "white",
    height: Layout.normalize(150),
    width: Layout.normalize(50),
    borderRadius: Layout.normalize(50),
    position: "absolute",
    bottom: 0,
    right: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  linkPreviewImageView: {
    marginLeft: Layout.normalize(10),
    marginTop: Layout.normalize(10),
  },
  tapAndHold: {
    opacity: Layout.normalize(0.8),
    backgroundColor: "black",
    padding: Layout.normalize(10),
    position: "absolute",
    bottom: Layout.normalize(80),
    right: Layout.normalize(35),
    borderRadius: Layout.normalize(10),
    borderBottomRightRadius: 0,
  },
  gifView: {
    backgroundColor: STYLES.$COLORS.MSG,
    paddingHorizontal: Layout.normalize(5),
    paddingVertical: Layout.normalize(3),
    borderRadius: Layout.normalize(5),
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginRight: Layout.normalize(10),
  },
  gifText: {
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    fontSize: STYLES.$FONT_SIZES.SMALL,
    color: "white",
    marginTop: Platform.OS === "ios" ? Layout.normalize(2) : 0,
  },
  paddingHorizontal: { paddingHorizontal: Layout.normalize(5) },
});
