import { Platform, StyleSheet } from "react-native";
import STYLES from "../../constants/Styles";
import Layout from "../../constants/Layout";

export const styles = StyleSheet.create({
  itemContainer: {
    flexDirection: "row",
    padding: STYLES.$PADDINGS.MEDIUM,
    alignItems: "center",
    backgroundColor: STYLES.$COLORS.TERTIARY,
  },
  avatar: {
    width: STYLES.$AVATAR.WIDTH,
    height: STYLES.$AVATAR.HEIGHT,
    borderRadius: STYLES.$AVATAR.BORDER_RADIUS,
    marginRight: STYLES.$MARGINS.SMALL,
  },
  lockIcon: {
    width: Layout.normalize(15),
    height: Layout.normalize(15),
    resizeMode: "contain",
    marginLeft: Layout.normalize(10),
  },
  secretInviteIcons: {
    width: Layout.normalize(15),
    height: Layout.normalize(15),
    resizeMode: "contain",
  },
  muteIcon: {
    width: Layout.normalize(17),
    height: Layout.normalize(17),
    resizeMode: "contain",
    marginLeft: Layout.normalize(10),
  },
  infoContainer: {
    flex: 1,
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Layout.normalize(8),
  },
  title: {
    fontSize: STYLES.$FONT_SIZES.XL,
    fontFamily: STYLES.$FONT_TYPES.BOLD,
    color: STYLES.$COLORS.FONT_PRIMARY,
    maxWidth: "80%",
  },
  time: {
    color: STYLES.$COLORS.MSG,
    fontSize: STYLES.$FONT_SIZES.SMALL,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
  },
  parentLastMessage: {
    color: STYLES.$COLORS.FONT_PRIMARY,
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
  },
  lastMessage: {
    color: STYLES.$COLORS.FONT_PRIMARY,
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
  },
  deletedMessage: {
    color: STYLES.$COLORS.FONT_PRIMARY,
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    fontStyle: "italic",
    width: "85%",
  },
  attachment_msg: {
    color: STYLES.$COLORS.FONT_PRIMARY,
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    marginRight: Layout.normalize(5),
    alignSelf: "flex-end",
    marginBottom:
      Platform.OS === "android" ? Layout.normalize(-3) : Layout.normalize(-1),
  },
  pinned: {
    width: Layout.normalize(20),
    height: Layout.normalize(20),
    backgroundColor: STYLES.$COLORS.PRIMARY,
    borderRadius: Layout.normalize(10),
    position: "absolute",
    top: Layout.normalize(16),
    right: Layout.normalize(16),
  },
  unreadCountContainer: {
    minWidth: Layout.normalize(25),
    minHeight: Layout.normalize(25),
    backgroundColor: STYLES.$COLORS.PRIMARY,
    borderRadius: Layout.normalize(15),
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    padding: Layout.normalize(5),
    bottom: Layout.normalize(16),
    right: Layout.normalize(15),
  },
  unreadCount: {
    color: STYLES.$COLORS.TERTIARY,
    fontSize: STYLES.$FONT_SIZES.SMALL,
    fontFamily: STYLES.$FONT_TYPES.SEMI_BOLD,
    marginTop:
      Platform.OS === "ios" ? Layout.normalize(2) : Layout.normalize(-1),
  },
  inviteIcon: {
    height: Layout.normalize(40),
    width: Layout.normalize(40),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: Layout.normalize(2),
    borderRadius: Layout.normalize(50),
    borderColor: "grey",
  },
  dmAvatarBubble: {
    backgroundColor: STYLES.$COLORS.SECONDARY,
    height: Layout.normalize(25),
    width: Layout.normalize(25),
    borderRadius: Layout.normalize(15),
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    bottom: Layout.normalize(-2),
    right: Layout.normalize(5),
  },
  dmAvatarBubbleImg: {
    height: Layout.normalize(13),
    width: Layout.normalize(13),
    resizeMode: "contain",
  },
  alignCenter: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
  },
  icon: {
    height: Layout.normalize(15),
    width: Layout.normalize(15),
    resizeMode: "contain",
    marginRight: Layout.normalize(5),
  },
  gifView: {
    backgroundColor: STYLES.$COLORS.MSG,
    paddingHorizontal: Layout.normalize(5),
    paddingVertical: Layout.normalize(3),
    borderRadius: Layout.normalize(5),
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  gifText: {
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    fontSize: STYLES.$FONT_SIZES.XS,
    color: "white",
    marginTop: Platform.OS === "ios" ? Layout.normalize(1) : 0,
  },
});
